from pathlib import Path


DATA_FOLDER_PATH = Path("./data")
OUT_FOLDER_PATH = Path("./out")
OUT_DATA_FOLDER_PATH = OUT_FOLDER_PATH / "data"
OUT_LOCALES_FOLDER_PATH = OUT_FOLDER_PATH / "locales"
MERGE_FOLDER_PATH = Path("./merge")
MERGED_DATA_FOLDER_PATH = MERGE_FOLDER_PATH / "data"
MERGED_LOCALES_FOLDER_PATH = MERGE_FOLDER_PATH / "locales"

IMAGES_FOLDER_PATH = Path("./images")
BUILDING_ICONS_FOLDER_PATH = IMAGES_FOLDER_PATH / "buildingIcons"
ITEM_ICONS_FOLDER_PATH = IMAGES_FOLDER_PATH / "items"

# file names
ITEMS = "items.json"
FULL_BOTTLES = "fullBottles.json"
FUEL = "fuel.json"
ITEM_FILTERS = "itemFilters.json"
CRAFTABLE_ITEMS = "craftableItems.json"
RESOURCE_POINTS = "resourcePoints.json"
ITEM_ID_TO_BUILDING_ID = "itemId2BuildingId.json"
BUILDINGS = "buildings.json"
CRAFTERS = "crafters.json"
MINERS = "miners.json"
PUMPS = "pumps.json"
POWER_STATIONS = "powerStations.json"
MACHINE_CRAFTS = "machineCrafts.json"
MACHINE_CRAFT_GROUPS = "machineCraftGroups.json"
MANUAL_CRAFTS = "manualCrafts.json"
HUB_CRAFTS = "hubCrafts.json"
ITEM_NAMES = "itemNames.json"
BUILDING_NAMES = "buildingNames.json"
RESOURCE_POINT_NAMES = "resourcePointNames.json"

# input locales
BR_PATH = DATA_FOLDER_PATH / "I18nTextTable_BR.json"
CN_PATH = DATA_FOLDER_PATH / "I18nTextTable_CN.json"
DE_PATH = DATA_FOLDER_PATH / "I18nTextTable_DE.json"
EN_PATH = DATA_FOLDER_PATH / "I18nTextTable_EN.json"
FR_PATH = DATA_FOLDER_PATH / "I18nTextTable_FR.json"
ID_PATH = DATA_FOLDER_PATH / "I18nTextTable_ID.json"
IT_PATH = DATA_FOLDER_PATH / "I18nTextTable_IT.json"
JP_PATH = DATA_FOLDER_PATH / "I18nTextTable_JP.json"
KR_PATH = DATA_FOLDER_PATH / "I18nTextTable_KR.json"
MX_PATH = DATA_FOLDER_PATH / "I18nTextTable_MX.json"
RU_PATH = DATA_FOLDER_PATH / "I18nTextTable_RU.json"
TC_PATH = DATA_FOLDER_PATH / "I18nTextTable_TC.json"
TH_PATH = DATA_FOLDER_PATH / "I18nTextTable_TH.json"
VN_PATH = DATA_FOLDER_PATH / "I18nTextTable_VN.json"

#output locales
DE_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "de"
EN_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "en"
ES_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "es"
FR_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "fr"
ID_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "id"
IT_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "it"
JA_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "ja"
KO_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "ko"
PT_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "pt"
RU_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "ru"
TH_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "th"
VI_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "vi"
ZHCN_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "zhcn"
ZHTW_OUT_PATH = OUT_LOCALES_FOLDER_PATH / "zhtw"

# merged locales files
MERGED_DE_PATH = MERGED_LOCALES_FOLDER_PATH / "de"
MERGED_EN_PATH = MERGED_LOCALES_FOLDER_PATH / "en"
MERGED_ES_PATH = MERGED_LOCALES_FOLDER_PATH / "es"
MERGED_FR_PATH = MERGED_LOCALES_FOLDER_PATH / "fr"
MERGED_ID_PATH = MERGED_LOCALES_FOLDER_PATH / "id"
MERGED_IT_PATH = MERGED_LOCALES_FOLDER_PATH / "it"
MERGED_JA_PATH = MERGED_LOCALES_FOLDER_PATH / "ja"
MERGED_KO_PATH = MERGED_LOCALES_FOLDER_PATH / "ko"
MERGED_PT_PATH = MERGED_LOCALES_FOLDER_PATH / "pt"
MERGED_RU_PATH = MERGED_LOCALES_FOLDER_PATH / "ru"
MERGED_TH_PATH = MERGED_LOCALES_FOLDER_PATH / "th"
MERGED_VI_PATH = MERGED_LOCALES_FOLDER_PATH / "vi"
MERGED_ZHCN_PATH = MERGED_LOCALES_FOLDER_PATH / "zhcn"
MERGED_ZHTW_PATH = MERGED_LOCALES_FOLDER_PATH / "zhtw"

# input files
ITEM_TABLE_PATH =                          DATA_FOLDER_PATH / "ItemTable.json"
FULL_BOTTLE_TABLE_PATH =                   DATA_FOLDER_PATH / "FullBottleTable.json"
FACTORY_MACHINE_CRAFT_TABLE_PATH =         DATA_FOLDER_PATH / "FactoryMachineCraftTable.json"
FACTORY_MACHINE_CRAFT_GROUP_TABLE_PATH =   DATA_FOLDER_PATH / "FactoryMachineCraftGroupTable.json"
FACTORY_MANUAL_CRAFT_TABLE_PATH =          DATA_FOLDER_PATH / "FactoryManualCraftTable.json"
FACTORY_HUB_CRAFT_TABLE_PATH =             DATA_FOLDER_PATH / "FactoryHubCraftTable.json"
FACTORY_MACHINE_CRAFTER_TABLE_PATH =       DATA_FOLDER_PATH / "FactoryMachineCrafterTable.json"
FACTORY_FUEL_ITEM_TABLE_PATH =             DATA_FOLDER_PATH / "FactoryFuelItemTable.json"
FACTORY_POWER_STATION_TABLE_PATH =         DATA_FOLDER_PATH / "FactoryPowerStationTable.json"
FACTORY_MINER_TABLE_PATH =                 DATA_FOLDER_PATH / "FactoryMinerTable.json"
FACTORY_BUILDING_ITEM_REVERSE_TABLE_PATH = DATA_FOLDER_PATH / "FactoryBuildingItemReverseTable.json"
FACTORY_FLUID_PUMP_IN_TABLE_PATH =         DATA_FOLDER_PATH / "FactoryFluidPumpInTable.json"
ITEM_TYPE_TABLE_PATH =                     DATA_FOLDER_PATH / "ItemTypeTable.json"
WIKI_GROUP_TABLE_PATH =                    DATA_FOLDER_PATH / "WikiGroupTable.json"
WIKI_ENTRY_DATA_TABLE_PATH =               DATA_FOLDER_PATH / "WikiEntryDataTable.json"
FACTORY_BUILDING_TABLE_PATH =              DATA_FOLDER_PATH / "FactoryBuildingTable.json"
LIQUID_TABLE_PATH =                        DATA_FOLDER_PATH / "LiquidTable.json"
WIKI_ENEMY_DROP_TABLE_PATH =               DATA_FOLDER_PATH / "WikiEnemyDropTable.json"

# output files
MACHINE_CRAFT_TABLE_PATH =    OUT_DATA_FOLDER_PATH / MACHINE_CRAFTS
MACHINE_CRAFT_GROUP_PATH =    OUT_DATA_FOLDER_PATH / MACHINE_CRAFT_GROUPS
MACHINE_CRAFTERS_PATH =       OUT_DATA_FOLDER_PATH / CRAFTERS
FUEL_PATH =                   OUT_DATA_FOLDER_PATH / FUEL
POWER_STATIONS_PATH =         OUT_DATA_FOLDER_PATH / POWER_STATIONS
MINERS_PATH =                 OUT_DATA_FOLDER_PATH / MINERS
FLUID_PUMPS_PATH =            OUT_DATA_FOLDER_PATH / PUMPS
BUILDINGS_PATH =              OUT_DATA_FOLDER_PATH / BUILDINGS
ITEM_ID_TO_BUILDING_ID_PATH = OUT_DATA_FOLDER_PATH / ITEM_ID_TO_BUILDING_ID
FULL_BOTTLES_PATH =           OUT_DATA_FOLDER_PATH / FULL_BOTTLES
MANUAL_CRAFTS_PATH =          OUT_DATA_FOLDER_PATH / MANUAL_CRAFTS
BUILDING_CRAFTS_PATH =        OUT_DATA_FOLDER_PATH / HUB_CRAFTS
ITEMS_PATH =                  OUT_DATA_FOLDER_PATH / ITEMS
ITEM_GROUPS_PATH =            OUT_DATA_FOLDER_PATH / "itemGroups.json"
CRAFTABLE_ITEMS_PATH =        OUT_DATA_FOLDER_PATH / CRAFTABLE_ITEMS
ITEM_SUB_GROUP_LIST_PATH =    OUT_DATA_FOLDER_PATH / "itemSubGroupList.json"
RESOURCE_POINTS_PATH =        OUT_DATA_FOLDER_PATH / RESOURCE_POINTS
ITEM_FILTERS_PATH =           OUT_DATA_FOLDER_PATH / ITEM_FILTERS
ITEM_TYPES_PATH =             OUT_DATA_FOLDER_PATH / "itemTypes.json"
ITEM_MATERIALS_PATH =         OUT_DATA_FOLDER_PATH / "itemMaterials.json"

# merged data files
MERGED_ITEMS_PATH =                  MERGED_DATA_FOLDER_PATH / ITEMS
MERGED_FULL_BOTTLES_PATH =           MERGED_DATA_FOLDER_PATH / FULL_BOTTLES
MERGED_FUEL_PATH =                   MERGED_DATA_FOLDER_PATH / FUEL
MERGED_CRAFTABLE_ITEMS_PATH =        MERGED_DATA_FOLDER_PATH / CRAFTABLE_ITEMS
MERGED_RESOURCE_POINTS_PATH =        MERGED_DATA_FOLDER_PATH / RESOURCE_POINTS
MERGED_ITEM_ID_TO_BUILDING_ID_PATH = MERGED_DATA_FOLDER_PATH / ITEM_ID_TO_BUILDING_ID
MERGED_BUILDINGS_PATH =              MERGED_DATA_FOLDER_PATH / BUILDINGS
MERGED_CRAFTERS_PATH =               MERGED_DATA_FOLDER_PATH / CRAFTERS
MERGED_MINERS_PATH =                 MERGED_DATA_FOLDER_PATH / MINERS
MERGED_PUMPS_PATH =                  MERGED_DATA_FOLDER_PATH / PUMPS
MERGED_POWER_STATIONS_PATH =         MERGED_DATA_FOLDER_PATH / POWER_STATIONS
MERGED_MACHINE_CRAFTS_PATH =         MERGED_DATA_FOLDER_PATH / MACHINE_CRAFTS
MERGED_MACHINE_CRAFT_GROUPS_PATH =   MERGED_DATA_FOLDER_PATH / MACHINE_CRAFT_GROUPS
MERGED_MANUAL_CRAFTS_PATH =          MERGED_DATA_FOLDER_PATH / MANUAL_CRAFTS
MERGED_HUB_CRAFTS_PATH =             MERGED_DATA_FOLDER_PATH / HUB_CRAFTS
